"""Add PaymentToken

Revision ID: 3dba97f12c6e
Revises: 5619444fc259
Create Date: 2026-09-05 01:28:30.044804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '3dba97f12c6e'
down_revision: Union[str, None] = '5619444fc259'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('razorpay_customer_id', sa.String(), nullable=False),
    sa.Column('razorpay_token_id', sa.String(), nullable=False),
    sa.Column('card_last4', sa.String(), nullable=True),
    sa.Column('method_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_tokens_user_id'), 'payment_tokens', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_tokens_user_id'), table_name='payment_tokens')
    op.drop_table('payment_tokens')
    # ### end Alembic commands ###
