"""Add UserPaymentMethod

Revision ID: 5619444fc259
Revises: c89d16339056
Create Date: 2026-09-04 16:09:32.480534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '5619444fc259'
down_revision: Union[str, None] = 'c89d16339056'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_payment_methods',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('razorpay_customer_id', sa.String(), nullable=True),
    sa.Column('razorpay_token_id', sa.String(), nullable=False),
    sa.Column('method_type', sa.String(), nullable=False),
    sa.Column('last_four', sa.String(), nullable=True),
    sa.Column('is_default', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_payment_methods_user_id'), 'user_payment_methods', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_payment_methods_user_id'), table_name='user_payment_methods')
    op.drop_table('user_payment_methods')
    # ### end Alembic commands ###
