"""Init Phase 1

Revision ID: c89d16339056
Revises: 
Create Date: 2026-09-04 04:41:48.915774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c89d16339056'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('log_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_name', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('input_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reasoning', sa.String(), nullable=True),
    sa.Column('prev_hash', sa.String(), nullable=True),
    sa.Column('curr_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('intent_mandates',
    sa.Column('mandate_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('constraints', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('completeness', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('mandate_id')
    )
    op.create_table('merchants',
    sa.Column('merchant_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('schema_version', sa.String(), nullable=True),
    sa.Column('raw_schema_notes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('merchant_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('coupons',
    sa.Column('coupon_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('discount_type', sa.String(), nullable=False),
    sa.Column('discount_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('applicable_category', sa.String(), nullable=True),
    sa.Column('min_order_value', sa.Numeric(precision=10, scale=2), server_default=sa.text('0.0'), nullable=False),
    sa.Column('max_discount_cap', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('valid_from', sa.DateTime(), nullable=True),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.CheckConstraint("discount_type IN ('flat', 'percentage')", name='check_discount_type'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.merchant_id'], ),
    sa.PrimaryKeyConstraint('coupon_id')
    )
    op.create_index('ix_merchant_coupon', 'coupons', ['merchant_id', 'code'], unique=True)
    op.create_table('products',
    sa.Column('product_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('merchant_sku', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('raw_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('normalized', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(), server_default='INR', nullable=False),
    sa.Column('stock', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('rating', sa.Numeric(precision=2, scale=1), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.merchant_id'], ),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_index('ix_merchant_sku', 'products', ['merchant_id', 'merchant_sku'], unique=True)
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_table('cart_mandates',
    sa.Column('mandate_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('intent_mandate_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('coupon_id', sa.UUID(), nullable=True),
    sa.Column('price_at_selection', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payable_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.coupon_id'], ),
    sa.ForeignKeyConstraint(['intent_mandate_id'], ['intent_mandates.mandate_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('mandate_id')
    )
    op.create_table('payment_mandates',
    sa.Column('mandate_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('cart_mandate_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('authorization_type', sa.String(), nullable=False),
    sa.Column('authorized_at', sa.DateTime(), nullable=True),
    sa.Column('razorpay_order_id', sa.String(), nullable=True),
    sa.Column('razorpay_payment_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), server_default='pending', nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("authorization_type IN ('auto', 'user_confirmed')", name='check_auth_type'),
    sa.CheckConstraint("status IN ('pending', 'captured', 'failed', 'refunded')", name='check_payment_status'),
    sa.ForeignKeyConstraint(['cart_mandate_id'], ['cart_mandates.mandate_id'], ),
    sa.PrimaryKeyConstraint('mandate_id'),
    sa.UniqueConstraint('idempotency_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment_mandates')
    op.drop_table('cart_mandates')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_index('ix_merchant_sku', table_name='products')
    op.drop_table('products')
    op.drop_index('ix_merchant_coupon', table_name='coupons')
    op.drop_table('coupons')
    op.drop_table('merchants')
    op.drop_table('intent_mandates')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
